export const products = [
  {
    product_id: 1,
    name: "Muffin Chocolate Individual Wrap",
    description: "Pork - Tenderloin, Frozen",
    category: "Biscuits",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 48.67",
    retailPrice: "Rs. 8.85",
    discount: 1,
    barcode: "55154-5980",
    supplier_id: 98,
  },
  {
    product_id: 2,
    name: "Longos - Greek Salad",
    description: "Wild Boar - Tenderloin",
    category: "Salad",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 37.82",
    retailPrice: "Rs. 11.55",
    discount: 1,
    barcode: "51824-022",
    supplier_id: 24,
  },
  {
    product_id: 3,
    name: "Wine - Guy Sage Touraine",
    description: "Wine - Sauvignon Blanc Oyster",
    category: "Liquor",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 24.08",
    retailPrice: "Rs. 13.25",
    discount: 1,
    barcode: "54575-228",
    supplier_id: 47,
  },
  {
    product_id: 4,
    name: "Oil - Coconut",
    description: "Pie Shell - 9",
    category: "Biscuits|Snacks",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 20.87",
    retailPrice: "Rs. 4.96",
    discount: 1,
    barcode: "50881-020",
    supplier_id: 94,
  },
  {
    product_id: 5,
    name: "Lemon Tarts",
    description: "Sauce - Oyster",
    category: "sweet",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 14.20",
    retailPrice: "Rs. 0.02",
    discount: 1,
    barcode: "0168-0353",
    supplier_id: 71,
  },
  {
    product_id: 6,
    name: "Sea Bass - Whole",
    description: "Cheese - Roquefort Pappillon",
    category: "Cheese",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 23.41",
    retailPrice: "Rs. 3.13",
    discount: 1,
    barcode: "63739-800",
    supplier_id: 74,
  },
  {
    product_id: 7,
    name: "Tea - Decaf 1 Cup",
    description: "Black Currants",
    category: "Tea",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 22.49",
    retailPrice: "Rs. 3.25",
    discount: 1,
    barcode: "67777-235",
    supplier_id: 69,
  },
  {
    product_id: 8,
    name: "Wine - Ej Gallo Sonoma",
    description: "Cheese - Perron Cheddar",
    category: "Wine|Beer|Spirit",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 30.56",
    retailPrice: "Rs. 33.08",
    discount: 1,
    barcode: "13734-130",
    supplier_id: 94,
  },
  {
    product_id: 9,
    name: "Pasta - Canelloni, Single Serve",
    description: "Chicken - Wieners",
    category: "foods",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 25.99",
    retailPrice: "Rs. 0.55",
    discount: 1,
    barcode: "56062-434",
    supplier_id: 55,
  },
  {
    product_id: 10,
    name: "Celery Root",
    description: "Hipnotiq Liquor",
    category: "Liquor",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 19.75",
    retailPrice: "Rs. 9.22",
    discount: 1,
    barcode: "62670-4359",
    supplier_id: 29,
  },
  {
    product_id: 11,
    name: "Soup - Cream Of Broccoli",
    description: "Pears - Bosc",
    category: "Soup",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 20.40",
    retailPrice: "Rs. 19.36",
    discount: 1,
    barcode: "57955-5159",
    supplier_id: 27,
  },
  {
    product_id: 12,
    name: "Cake - French Pear Tart",
    description: "Cheese - Brie, Triple Creme",
    category: "Cheese",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 17.94",
    retailPrice: "Rs. 34.38",
    discount: 1,
    barcode: "17518-054",
    supplier_id: 38,
  },
  {
    product_id: 13,
    name: "Chocolate - Pistoles, Lactee, Milk",
    description: "Dates",
    category: "Nuts|snack",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 3.38",
    retailPrice: "Rs. 23.67",
    discount: 1,
    barcode: "0615-7555",
    supplier_id: 67,
  },
  {
    product_id: 14,
    name: "Cherries - Bing, Canned",
    description: "Flour - So Mix Cake White",
    category: "Biscuits|Snacks|sweet",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 34.16",
    retailPrice: "Rs. 31.62",
    discount: 1,
    barcode: "49349-119",
    supplier_id: 100,
  },
  {
    product_id: 15,
    name: "Sauce - White, Mix",
    description: "Olives - Black, Pitted",
    category: "Sauce|Snacks|sweet",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 41.63",
    retailPrice: "Rs. 27.65",
    discount: 1,
    barcode: "24653-801",
    supplier_id: 64,
  },
  {
    product_id: 16,
    name: "Pear - Halves",
    description: "Artichokes - Knobless, White",
    category: "Snacks|sweet|Tea",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 38.79",
    retailPrice: "Rs. 11.28",
    discount: 1,
    barcode: "52033-001",
    supplier_id: 26,
  },
  {
    product_id: 17,
    name: "Snapple Lemon Tea",
    description: "Rum - Cream, Amarula",
    category: "Tea|sweet|Western",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 48.08",
    retailPrice: "Rs. 29.68",
    discount: 1,
    barcode: "65044-5049",
    supplier_id: 45,
  },
  {
    product_id: 18,
    name: "Venison - Denver Leg Boneless",
    description: "Cakes Assorted",
    category: "Biscuits|Snacks|sweet|Tea|Western",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 24.85",
    retailPrice: "Rs. 29.51",
    discount: 1,
    barcode: "55154-1610",
    supplier_id: 85,
  },
  {
    product_id: 19,
    name: "Hold Up Tool Storage Rack",
    description: "Pepper - Cayenne",
    category: "Biscuits|Snacks|sweet|Tea|Western",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 8.53",
    retailPrice: "Rs. 4.92",
    discount: 1,
    barcode: "0054-3194",
    supplier_id: 51,
  },
  {
    product_id: 20,
    name: "Beef - Rib Roast, Capless",
    description: "Wine - Niagara Peninsula Vqa",
    category: "Liquor",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 29.53",
    retailPrice: "Rs. 49.83",
    discount: 1,
    barcode: "59779-908",
    supplier_id: 88,
  },
  {
    product_id: 21,
    name: "Ice Cream Bar - Oreo Sandwich",
    description: "Wine - Cava Aria Estate Brut",
    category: "sweet|Tea|Western",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 35.20",
    retailPrice: "Rs. 2.32",
    discount: 1,
    barcode: "58232-4001",
    supplier_id: 94,
  },
  {
    product_id: 22,
    name: "Wine - Rosso Del Veronese Igt",
    description: "Wine - Red, Gamay Noir",
    category: "liquor|sweet|Tea|Western",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 3.76",
    retailPrice: "Rs. 0.33",
    discount: 1,
    barcode: "66382-299",
    supplier_id: 90,
  },
  {
    product_id: 23,
    name: "Swiss Chard",
    description: "Russian Prince",
    category: "Sweet|Snack",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 6.47",
    retailPrice: "Rs. 30.59",
    discount: 1,
    barcode: "0781-1832",
    supplier_id: 22,
  },
  {
    product_id: 24,
    name: "Apple - Northern Spy",
    description: "Sun - Dried Tomatoes",
    category: "Sweet|Snack",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 20.31",
    retailPrice: "Rs. 48.53",
    discount: 1,
    barcode: "0781-5618",
    supplier_id: 2,
  },
  {
    product_id: 25,
    name: "Onions - Cippolini",
    description: "Cheese - Manchego, Spanish",
    category: "Sweet|Snack",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 49.09",
    retailPrice: "Rs. 49.84",
    discount: 1,
    barcode: "65862-156",
    supplier_id: 28,
  },
  {
    product_id: 26,
    name: "Appetizer - Tarragon Chicken",
    description: "Beef - Sushi Flat Iron Steak",
    category: "Sweet|Snack",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 26.81",
    retailPrice: "Rs. 39.47",
    discount: 1,
    barcode: "43538-600",
    supplier_id: 27,
  },
  {
    product_id: 27,
    name: "Ham - Procutinni",
    description: "Veal - Leg",
    category: "Sweet|Snack",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 6.91",
    retailPrice: "Rs. 0.50",
    discount: 1,
    barcode: "50988-198",
    supplier_id: 70,
  },
  {
    product_id: 28,
    name: "Pepper - Red, Finger Hot",
    description: "Fruit Salad Deluxe",
    category: "Sweet|Snack",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 46.80",
    retailPrice: "Rs. 12.56",
    discount: 1,
    barcode: "59478-000",
    supplier_id: 92,
  },
  {
    product_id: 29,
    name: "Soup - Campbells, Cream Of",
    description: "Oil - Pumpkinseed",
    category: "Sweet|Snack",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 43.54",
    retailPrice: "Rs. 24.24",
    discount: 1,
    barcode: "54868-4992",
    supplier_id: 49,
  },
  {
    product_id: 30,
    name: "Fond - Neutral",
    description: "Langers - Cranberry Cocktail",
    category: "Sweet|Snack",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 20.27",
    retailPrice: "Rs. 44.85",
    discount: 1,
    barcode: "68752-034",
    supplier_id: 73,
  },
  {
    product_id: 31,
    name: "Rye Special Old",
    description: "Cocktail Napkin Blue",
    category: "Sweet|Snack",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 17.03",
    retailPrice: "Rs. 32.22",
    discount: 1,
    barcode: "50436-6462",
    supplier_id: 20,
  },
  {
    product_id: 32,
    name: "Wine - Jafflin Bourgongone",
    description: "Jam - Blackberry, 20 Ml Jar",
    category: "Sweet|Snack",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 28.90",
    retailPrice: "Rs. 41.35",
    discount: 1,
    barcode: "0574-0815",
    supplier_id: 33,
  },
  {
    product_id: 33,
    name: "Sugar - Invert",
    description: "Pasta - Cheese / Spinach Bauletti",
    category: "Sweet|Snack",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 46.05",
    retailPrice: "Rs. 28.17",
    discount: 1,
    barcode: "0781-5608",
    supplier_id: 92,
  },
  {
    product_id: 34,
    name: "Duck - Fat",
    description: "Flavouring - Raspberry",
    category: "Sweet|Snack",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 7.03",
    retailPrice: "Rs. 49.74",
    discount: 1,
    barcode: "0268-1126",
    supplier_id: 75,
  },
  {
    product_id: 35,
    name: "Steamers White",
    description: "Wine - White Cab Sauv.on",
    category: "Sweet|Snack",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 49.93",
    retailPrice: "Rs. 47.48",
    discount: 1,
    barcode: "57520-0292",
    supplier_id: 85,
  },
  {
    product_id: 36,
    name: "Stock - Beef, White",
    description: "Cake - Dulce De Leche",
    category: "Sweet|Snack",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 0.00",
    retailPrice: "Rs. 20.61",
    discount: 1,
    barcode: "35378-0006",
    supplier_id: 3,
  },
  {
    product_id: 37,
    name: "Jolt Cola - Red Eye",
    description: "Garbag Bags - Black",
    category: "Sweet|Snack",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 11.42",
    retailPrice: "Rs. 14.61",
    discount: 1,
    barcode: "0781-1375",
    supplier_id: 88,
  },
  {
    product_id: 38,
    name: "Chocolate - Compound Coating",
    description: "Blueberries",
    category: "Sweet|Snack",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 20.46",
    retailPrice: "Rs. 29.87",
    discount: 1,
    barcode: "62296-0023",
    supplier_id: 68,
  },
  {
    product_id: 39,
    name: "Cheese - Cheddarsliced",
    description: "Veal - Shank, Pieces",
    category: "Sweet|Snack",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 37.35",
    retailPrice: "Rs. 41.16",
    discount: 1,
    barcode: "75930-001",
    supplier_id: 44,
  },
  {
    product_id: 40,
    name: "Onions - Cooking",
    description: "Lettuce Romaine Chopped",
    category: "Sweet|Snack",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 35.62",
    retailPrice: "Rs. 13.30",
    discount: 1,
    barcode: "50419-254",
    supplier_id: 9,
  },
  {
    product_id: 41,
    name: "Calaloo",
    description: "Lemons",
    category: "Sweet|Snack",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 20.89",
    retailPrice: "Rs. 20.55",
    discount: 1,
    barcode: "63739-375",
    supplier_id: 74,
  },
  {
    product_id: 42,
    name: "Lemon Tarts",
    description: "Pate Pans Yellow",
    category: "Sweet|Snack",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 18.00",
    retailPrice: "Rs. 8.81",
    discount: 1,
    barcode: "63629-3380",
    supplier_id: 10,
  },
  {
    product_id: 43,
    name: "Pasta - Cannelloni, Sheets, Fresh",
    description: "Chocolate - Mi - Amere Semi",
    category: "Sweet|Snack",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 33.56",
    retailPrice: "Rs. 27.75",
    discount: 1,
    barcode: "0067-8114",
    supplier_id: 66,
  },
  {
    product_id: 44,
    name: "Bagel - Whole White Sesame",
    description: "Sour Puss - Tangerine",
    category: "Sweet|Snack",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 48.31",
    retailPrice: "Rs. 13.60",
    discount: 1,
    barcode: "0363-5336",
    supplier_id: 3,
  },
  {
    product_id: 45,
    name: "Sobe - Lizard Fuel",
    description: "Cabbage - Savoy",
    category: "Sweet|Snack",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 18.91",
    retailPrice: "Rs. 38.56",
    discount: 1,
    barcode: "49580-1108",
    supplier_id: 44,
  },
  {
    product_id: 46,
    name: "Oxtail - Cut",
    description: "Spring Roll Veg Mini",
    category: "Sweet|Snack",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 49.32",
    retailPrice: "Rs. 48.07",
    discount: 1,
    barcode: "43406-0071",
    supplier_id: 29,
  },
  {
    product_id: 47,
    name: "Mushroom - Enoki, Dry",
    description: "Wine - Red, Pinot Noir, Chateau",
    category: "Sweet|Snack",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 40.09",
    retailPrice: "Rs. 41.33",
    discount: 1,
    barcode: "0603-3442",
    supplier_id: 70,
  },
  {
    product_id: 48,
    name: "Beef - Ox Tongue",
    description: "Boogies",
    category: "Sweet|Snack",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 12.32",
    retailPrice: "Rs. 3.32",
    discount: 1,
    barcode: "60793-434",
    supplier_id: 10,
  },
  {
    product_id: 49,
    name: "Bread - Rolls, Rye",
    description: "Energy - Boo - Koo",
    category: "Sweet|Snack",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 13.76",
    retailPrice: "Rs. 17.00",
    discount: 1,
    barcode: "67046-031",
    supplier_id: 18,
  },
  {
    product_id: 50,
    name: "Propel Sport Drink",
    description: "Cheese - Mozzarella, Buffalo",
    category: "Sweet|Snack",
    image: [
      "https://placehold.co/600x400/png",
      "https://placehold.co/200x200/png",
      "https://placehold.co/200x200/png",
    ],
    weight: 100,
    unit: 1,
    buyingPrice: "Rs. 14.84",
    retailPrice: "Rs. 10.01",
    discount: 1,
    barcode: "57844-716",
    supplier_id: 77,
  },
];

export function getProducts() {
  return products;
}

export function getProduct(id) {
  return products.find((c) => c.product_id === id);
}

export function saveProduct(product) {
  let productInDb =
    products.find((c) => c.product_id === product.product_id) || {};
  productInDb.name = product.name;
  productInDb.description = product.description;
  productInDb.category = product.category;
  productInDb.image = product.image
    ? product.image
    : [
        "https://placehold.co/600x400/png",
        "https://placehold.co/200x200/png",
        "https://placehold.co/200x200/png",
      ];
  productInDb.weight = product.weight;
  productInDb.unit = product.unit;
  productInDb.buyingPrice = product.buyingPrice;
  productInDb.retailPrice = product.retailPrice;
  productInDb.barcode = product.barcode;
  productInDb.supplier_id = product.supplier_id;

  if (!productInDb.product_id) {
    productInDb.product_id = products.length + 1;
    products.push(productInDb);
  }

  console.log("saved", productInDb);
  return productInDb;
}
